Regenerated configure, improved mkChangeLog.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8773,10 +8773,14 @@ fi
 echo "$as_me:8773: result: $ac_cv_func_gettext" >&5
 echo "${ECHO_T}$ac_cv_func_gettext" >&6
 
-  cat >>confdefs.h <<\EOF
+  if test "x$ac_cv_func_gettext" = xyes; then
+    cat >>confdefs.h <<\EOF
 #define HAVE_GETTEXT 1
 EOF
 
+  else
+    i18n=no
+  fi
 fi
 echo "------------------------------------------------------------"
 echo "Available drivers:"
@@ -8989,7 +8993,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:8992: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:8996: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -9162,7 +9166,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:9165: error: ambiguous option: $1
+    { { echo "$as_me:9169: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -9181,7 +9185,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:9184: error: unrecognized option: $1
+  -*) { { echo "$as_me:9188: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -9232,7 +9236,7 @@ do
   "src/ui/ui-drv/win32/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/ui/ui-drv/win32/Makefile" ;;
   "src/ui/ui-drv/BeOS/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/ui/ui-drv/BeOS/Makefile" ;;
   "src/include/aconfig.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/include/aconfig.h" ;;
-  *) { { echo "$as_me:9235: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:9239: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -9360,6 +9364,7 @@ s,@DRIVERDIRS@,$DRIVERDIRS,;t t
 s,@STICKY@,$STICKY,;t t
 s,@CFLAGS1@,$CFLAGS1,;t t
 s,@ASMOBJS@,$ASMOBJS,;t t
+s,@i18n@,$i18n,;t t
 CEOF
 
 EOF
@@ -9474,7 +9479,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:9477: creating $ac_file" >&5
+    { echo "$as_me:9482: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -9492,7 +9497,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:9495: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:9500: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -9505,7 +9510,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:9508: error: cannot find input file: $f" >&5
+           { { echo "$as_me:9513: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -9566,7 +9571,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:9569: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:9574: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -9577,7 +9582,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:9580: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:9585: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -9590,7 +9595,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:9593: error: cannot find input file: $f" >&5
+           { { echo "$as_me:9598: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -9707,7 +9712,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:9710: $ac_file is unchanged" >&5
+      { echo "$as_me:9715: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -9782,50 +9787,44 @@ echo " CFLAGS1     : $CFLAGS1"
 echo " CXXFLAGS    : $CXXFLAGS"
 echo " LDLAGS      : $LDLAGS"
 echo " LIBS        : $LIBS"
-echo " X_LIBS        : $X_LIBS"
+echo " X_LIBS      : $X_LIBS"
 echo "------------------------------------------------------------"
 echo " "
 echo "READ CUREFULLY FOLLOWING WARNINGS"
 echo " "
 if test "x$ac_cv_header_stdc" = xno; then
-  { echo "$as_me:9791: WARNING: There is no ansi c headers avaiable. XaoS will have troubles with compiling." >&5
-echo "$as_me: WARNING: There is no ansi c headers avaiable. XaoS will have troubles with compiling." >&2;}
+  { echo "$as_me:9796: WARNING: There are no ANSI C headers avaiable. XaoS will have troubles with compiling." >&5
+echo "$as_me: WARNING: There are no ANSI C headers avaiable. XaoS will have troubles with compiling." >&2;}
   config_problem=yes
 fi
 if test "x$ac_cv_c_compiler_gnu" = xyes; then
   echo
 else
-  { echo "$as_me:9798: WARNING: The gnu c compiler is recomended to get best performance. XaoS crashes many compiler so your compiler can cause troubles." >&5
-echo "$as_me: WARNING: The gnu c compiler is recomended to get best performance. XaoS crashes many compiler so your compiler can cause troubles." >&2;}
+  { echo "$as_me:9803: WARNING: The GNU C compiler is recommended to get the best performance. XaoS crashes many compilers so your compiler can cause troubles." >&5
+echo "$as_me: WARNING: The GNU C compiler is recommended to get the best performance. XaoS crashes many compilers so your compiler can cause troubles." >&2;}
 fi
 if test "x$ac_cv_c_long_double" = xyes; then
   if test "x$long_double" = xyes; then
-  { echo "$as_me:9803: WARNING: Long double enabled. This works well for x86 architectures. On other systems this should slow down much. Especially on sun workstations. If XaoS works incredibly slowly try to rebuild it using:
-   configure --with-long-double=no
-   make clean
-   make" >&5
-echo "$as_me: WARNING: Long double enabled. This works well for x86 architectures. On other systems this should slow down much. Especially on sun workstations. If XaoS works incredibly slowly try to rebuild it using:
-   configure --with-long-double=no
-   make clean
-   make" >&2;}
+  { echo "$as_me:9808: WARNING: Long double enabled. This works well for x86 architectures. On other systems this may slow down much. Especially on SUN workstations. If XaoS works incredibly slowly" >&5
+echo "$as_me: WARNING: Long double enabled. This works well for x86 architectures. On other systems this may slow down much. Especially on SUN workstations. If XaoS works incredibly slowly" >&2;}
   fi
 fi
 if test "x$drivers" = xno; then
-  { echo "$as_me:9814: WARNING: There is no driver avaible. XaoS will not start." >&5
+  { echo "$as_me:9813: WARNING: There is no driver avaible. XaoS will not start." >&5
 echo "$as_me: WARNING: There is no driver avaible. XaoS will not start." >&2;}
   config_problem=yes
 fi
 if test "x$config_problem" = xyes; then
-  { echo "$as_me:9819: WARNING: There was a problem with automatic configuration." >&5
+  { echo "$as_me:9818: WARNING: There was a problem with automatic configuration." >&5
 echo "$as_me: WARNING: There was a problem with automatic configuration." >&2;}
-  { echo "$as_me:9821: WARNING: Read INSTALL file for trouble-shooting tips." >&5
-echo "$as_me: WARNING: Read INSTALL file for trouble-shooting tips." >&2;}
+  { echo "$as_me:9820: WARNING: Read INSTALL file for troubleshooting tips." >&5
+echo "$as_me: WARNING: Read INSTALL file for troubleshooting tips." >&2;}
 fi
 if test x"$ac_cv_lib_z_inflate" = xno; then
  if test x"$ac_cv_lib_gz_inflate" = xno; then
   echo "You need zlib to compile XaoS with image saving code."
   echo "Please download it from:"
-  echo "  XaoS homepage at http://www.paru.cas.cz/~hubicka/XaoS"
+  echo "  XaoS homepage at http://xaos.sf.net"
   echo "  or ftp://sunsite.unc.edu/pub/Linux/libs"
   echo "  or ftp://ftp.uu.net/graphics/png/src/zlib-0.95.tar.gz"
   echo
@@ -9834,14 +9833,21 @@ fi
 if test x"$ac_cv_lib_png_png_create_info_struct" = xno; then
   echo "You need pnglib to compile XaoS with image saving code."
   echo "Please download it from:"
-  echo "  XaoS homepage at http://www.paru.cas.cz/~hubicka/XaoS"
+  echo "  XaoS homepage at http://xaos.sf.net"
   echo "  or ftp://sunsite.unc.edu/pub/Linux/libs"
   echo "  or ftp://ftp.uu.net/graphics/png/src/libpng-0.81.tar.gz"
+  echo
+fi
+if test x"$ac_cv_func_gettext" = xno; then
+  echo "You need GNU gettext to compile XaoS with internationalization support."
+  echo "Please download it from:"
+  echo "  XaoS homepage at http://xaos.sf.net"
+  echo "  or ftp://www.gnu.org/software/gettext/"
   echo
 fi
 echo " "
 echo "END OF WARNINGS"
 echo " "
 echo "In case you have troubles with compiling or running"
-echo "XaoS please read compilers.txt."
+echo "XaoS please read doc/compilers.txt."
 echo "------------------------------------------------------------"
