Fixes to windows build system

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4874,6 +4874,7 @@ echo "$as_me: error: Install the msgmerge utility first for i18n
       POFILES="$POFILES $lang.po"
     done
   fi
+  LIBS="$LIBS $LIBINTL"
 fi
 
 
@@ -7452,7 +7453,7 @@ fi
 done
 
   else
-    echo "No pthread library available! Can not compile threaded version"
+    echo "No pthread library available! Cannot compile threaded version"
     exit
   fi
   fi
@@ -9338,7 +9339,8 @@ done
 
 
 
-for ac_header in OS.h alloca.h ddraw.h htmlhelp.h errno.h fcntl.h float.h libintl.h limits.h locale.h malloc.h stddef.h stdlib.h string.h sys/time.h sys/timeb.h unistd.h
+
+for ac_header in OS.h alloca.h ddraw.h htmlhelp.h errno.h fcntl.h float.h iconv.h libintl.h limits.h locale.h malloc.h stddef.h stdlib.h string.h sys/time.h sys/timeb.h unistd.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -9695,7 +9697,7 @@ _ACEOF
 fi
 
 else
-echo Long double disabled, since it should be too slow at this CPU
+echo Long double disabled, since it would be too slow on this CPU
 fi
 echo "$as_me:$LINENO: checking whether time.h and sys/time.h may both be included" >&5
 echo $ECHO_N "checking whether time.h and sys/time.h may both be included... $ECHO_C" >&6
@@ -11484,6 +11486,70 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for libiconv_open in -liconv" >&5
+echo $ECHO_N "checking for libiconv_open in -liconv... $ECHO_C" >&6
+if test "${ac_cv_lib_iconv_libiconv_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-liconv  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char libiconv_open ();
+int
+main ()
+{
+libiconv_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_iconv_libiconv_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_iconv_libiconv_open=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_iconv_libiconv_open" >&5
+echo "${ECHO_T}$ac_cv_lib_iconv_libiconv_open" >&6
+if test $ac_cv_lib_iconv_libiconv_open = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBICONV 1
+_ACEOF
+
+  LIBS="-liconv $LIBS"
+
+fi
+
+
 if test $png = yes; then
 
 echo "$as_me:$LINENO: checking for inflate in -lz" >&5
@@ -12917,14 +12983,6 @@ if test "$ac_cv_header_ddraw_h" = "yes"; then
 #define DDRAW_DRIVER 1
 _ACEOF
 
- fi
-
-if test "$nls_cv_use_gnu_gettext" = yes; then
- cat >>confdefs.h <<\_ACEOF
-#define HAVE_GETTEXT 1
-_ACEOF
-
- LIBS="$LIBS -lintl"
  fi
 
 
@@ -14580,7 +14638,7 @@ echo " LIBS        : $LIBS"
 echo " X_LIBS      : $X_LIBS"
 echo "------------------------------------------------------------"
 echo " "
-echo "READ CUREFULLY FOLLOWING WARNINGS"
+echo "READ THE FOLLOWING WARNINGS CAREFULLY"
 echo " "
 if test "x$ac_cv_header_stdc" = xno; then
   { echo "$as_me:$LINENO: WARNING: There are no ANSI C headers avaiable. XaoS will have troubles with compiling." >&5
@@ -14619,17 +14677,11 @@ fi
 if test x"$ac_cv_lib_z_inflate" = xno; then
  if test x"$ac_cv_lib_gz_inflate" = xno; then
   echo "You need zlib to compile XaoS with image saving code."
-  echo "Please download it from:"
-  echo "  ftp://sunsite.unc.edu/pub/Linux/libs"
-  echo "  or ftp://ftp.uu.net/graphics/png/src/zlib-0.95.tar.gz"
   echo
  fi
 fi
 if test x"$ac_cv_lib_png_png_create_info_struct" = xno; then
   echo "You need pnglib to compile XaoS with image saving code."
-  echo "Please download it from:"
-  echo "  ftp://sunsite.unc.edu/pub/Linux/libs"
-  echo "  or ftp://ftp.uu.net/graphics/png/src/libpng-0.81.tar.gz"
   echo
 fi
 echo " "
