Finalize cmake build (also for wasm)

diff --git a/tools/postprocess-web b/tools/postprocess-web
--- a/tools/postprocess-web
+++ b/tools/postprocess-web
@@ -5,13 +5,13 @@
 
 set -e
 
-if [ "$1" = "" ]; then
- echo "Usage: $0 [bin-folder]"
+if [ $# != 2 ]; then
+ echo "Usage: $0 [source-folder] [build-folder]"
  exit 1
  fi
 
-test "$1/xaos.js" || {
- echo "The file $1/xaos.js is missing."
+test "$2/xaos.js" || {
+ echo "The file $2/xaos.js is missing."
  exit 2
  }
 
@@ -21,7 +21,8 @@ sed -i 's/Module\["print"\]/\
   let statustext = "STATUS: ";\
   if (t.startsWith(statustext)) document.title = t.substring(statustext.length);\
   }\
-/' "$1/xaos.js"
+/' "$2/xaos.js"
 # For a workaround on macOS, see https://stackoverflow.com/questions/12696125/sed-edit-file-in-place
 
-cp "$1/../src/ui/images/qtlogo.svg" "$1"
+cp "$1/src/ui/images/qtlogo.svg" "$2"
+exit 0
